// Bundles ../Data/*.json (the repo's shared data) into src/data.js so index.html works when opened
// straight from disk (file:// cannot fetch JSON). Run after editing the JSON:
//   node scripts/build_data.js
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = f => JSON.parse(fs.readFileSync(path.join(root, '..', 'Data', f), 'utf8'));
const out = `// GENERATED by scripts/build_data.js from Data/*.json. Do not edit by hand.
window.ORBITAL_ELEMENTS = ${JSON.stringify(read('orbital_elements.json'), null, 2)};
window.NETWORK_MODEL = ${JSON.stringify(read('network_model.json'), null, 2)};
`;
fs.writeFileSync(path.join(root, 'src', 'data.js'), out);
console.log('wrote src/data.js');
